package com.management.oop.project.commands.enums;

public enum CommandType {
    CREATENEWPERSON,
    SHOWALLPEOPLE,
    SHOWPERSONACTIVITY,
    CREATENEWTEAM,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITY,
    ADDPERSONTOTEAM,
    SHOWALLTEAMMEMBERS,
    CREATENEWBOARDS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CREATENEWBUGINBOARD,
    CREATENEWSTORYINBOARD,
    CREATENEWFEEDBACKINBOARD,
    CHANGEPRIORITYOFBUG,
    CHANGESEVERITYOFBUG,
    CHANGESTATUSOFBUG,
    CHANGEPRIORITYOFSTORY,
    CHANGESIZEOFSTORY,
    CHANGESTATUSOFSTORY,
    CHANGERATINGOFFEEDBACK,
    CHANGESTATUSOFFEEDBACK,
    ASSIGNTASKTOPERSON,
    UNASSIGNTASKTOPERSON

}
