package com.management.oop.project.commands.enums;

public enum CommandType {
    CREATENEWPERSON,
    SHOWALLPEOPLE,
    SHOWPERSONACTIVITY,
    CREATENEWTEAM,
    SHOWALLTEAMS,
    SHOWTEAMSACTIVITY,
    ADDPERSONTOTEAM,
    SHOWALLTEAMMEMBERS,
    CREATENEWBOARDS,
    SHOWALLTEAMBOARDS,
    SHOWBOARDACTIVITY,
    CREATENEWBUGINBOARD,
    CREATENEWSTORYINBOARD,
    CREATENEWFEEDBACKINBOARD,
    CHANGEBUG,
    CHANGEFEEDBACK,
    CHANGESTORY,
    ASSIGNTASKTOPERSON,
    UNASSIGNTASKTOPERSON

}
